name: GitHub Pages
run-name: ${{ github.actor }} ran this workflow

on: workflow_dispatch

defaults:
  run:
      working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: mkdir -v ../_site

      - run: npm ci
      - run: npm run build
      - run: mv -v dist/* ../_site

      - uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v2

    permissions:
      id-token: write
      pages: write
